name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: 'Test Object-Oriented Programming '
      id: test-object-oriented-programming
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-OBJECT-ORIENTED-PROGRAMMING_RESULTS: "${{steps.test-object-oriented-programming.outputs.result}}"
      with:
        runners: test-object-oriented-programming
